# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(601, 323)
        self.url_text = QtWidgets.QPlainTextEdit(Form)
        self.url_text.setGeometry(QtCore.QRect(10, 40, 581, 221))
        self.url_text.setObjectName("url_text")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.load_url_btn = QtWidgets.QPushButton(Form)
        self.load_url_btn.setGeometry(QtCore.QRect(430, 280, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.load_url_btn.setFont(font)
        self.load_url_btn.setObjectName("load_url_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Photo URL"))
        self.load_url_btn.setText(_translate("Form", "Load Image"))
